// Code generated by "stringer -type=EncodingType"; DO NOT EDIT.

package extras

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownEncoding-0]
	_ = x[Base64Encoding-1]
	_ = x[BCryptEncoding-2]
	_ = x[HexEncoding-3]
}

const _EncodingType_name = "UnknownEncodingBase64EncodingBCryptEncodingHexEncoding"

var _EncodingType_index = [...]uint8{0, 15, 29, 43, 54}

func (i EncodingType) String() string {
	if i < 0 || i >= EncodingType(len(_EncodingType_index)-1) {
		return "EncodingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EncodingType_name[_EncodingType_index[i]:_EncodingType_index[i+1]]
}
