// Code generated by "stringer -type=ExtenderType"; DO NOT EDIT.

package extras

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[YamlExtender-1]
	_ = x[Base64Extender-2]
	_ = x[RegexExtender-3]
	_ = x[JsonExtender-4]
}

const _ExtenderType_name = "UnknownYamlExtenderBase64ExtenderRegexExtenderJsonExtender"

var _ExtenderType_index = [...]uint8{0, 7, 19, 33, 46, 58}

func (i ExtenderType) String() string {
	if i < 0 || i >= ExtenderType(len(_ExtenderType_index)-1) {
		return "ExtenderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExtenderType_name[_ExtenderType_index[i]:_ExtenderType_index[i+1]]
}
