name: Test release

on:
  pull_request:
    branches: ["main"]

jobs:
  snapshot:
    name: Test GoReleaser Snapshot
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
      - name: Import Signature key
        shell: bash
        run: |
          echo -e "$GPG_PRIVATE_KEY" > gpg_key.asc
          openssl rsa -in gpg_key.asc -pubout -out kaweezle-devel@kaweezle.com-c9d89864.rsa.pub
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCOOP_BUCKET_GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      # - name: Build APK repo
      #   uses: ./.github/actions/make-apkindex
      #   with:
      #     apk_files: dist/*.apk
      #     signature_key: "${{ secrets.GPG_PRIVATE_KEY }}"
      #     signature_key_name: kaweezle-devel@kaweezle.com-c9d89864.rsa
      #     destination: dist/repo
      # - name: Commit repo to kaweezle.com
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.REPO_ACCESS_TOKEN }}
      #   with:
      #     source-directory: dist/repo
      #     destination-github-username: kaweezle
      #     destination-repository-name: kaweezle.github.io
      #     # TODO: replace with kaweezle-devel
      #     user-name: antoinemartin
      #     user-email: antoine@openance.com
      #     target-branch: release-krmfnbuiltin-test
      #     target-directory: docs/repo
      #     commit-message: krmfnbuiltin APK repo ${{ github.ref_name }}
